const admin = require('firebase-admin');
const serviceAccount = require('./women-safety-app-d3e9b-firebase-adminsdk-fbsvc-719d109d78.json');

// Initialize Firebase Admin
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: 'https://safeher-44741-default-rtdb.firebaseio.com'
});

const db = admin.firestore();

const motivationalQuotes = [
  "You are stronger than you think, braver than you believe, and more capable than you know.",
  "Every woman has the power to protect herself and others. You are that woman.",
  "Your safety is not a luxury, it's a right. Stand strong, stay safe.",
  "Courage doesn't mean you're not afraid. It means you don't let fear stop you.",
  "You are the hero of your own story. Trust your instincts, trust your strength.",
  "Empowered women empower women. Together we are unstoppable.",
  "Your voice matters, your safety matters, you matter.",
  "Strength comes from within. You have everything you need to protect yourself.",
  "Be bold, be brave, be beautiful. You are enough.",
  "Every step you take towards safety is a step towards empowerment.",
  "Never underestimate the power of a woman determined to stay safe.",
  "Every act of self-care is an act of self-defense.",
  "You are not alone. There is a whole community standing with you.",
  "Stand tall, even if your voice shakes.",
  "In any moment of decision, trust your intuition.",
  "You are not weak when you ask for help—you're wise.",
  "Safety begins with awareness. Stay alert, stay empowered.",
  "You are never too young or too old to be your own hero.",
  "A woman's worth is not measured by fear but by courage.",
  "Looking out for one another makes us all stronger.",
  "You have the right to walk without fear.",
  "Every boundary you set is an act of self-respect.",
  "You are unstoppable, no matter the challenge.",
  "Safety doesn't happen by accident. Trust yourself.",
  "Speak up, even if your voice trembles.",
  "Your life is precious—defend it fiercely.",
  "Staying safe is the highest form of self-love.",
  "Together, we are powerful beyond measure.",
  "Your instincts are your best line of defense.",
  "You are your own greatest protector.",
  "Never apologize for putting your safety first.",
  "Every time you walk away from danger, you win.",
  "Bravery is not the absence of fear, but determination in the face of it.",
  "Your confidence is your shield.",
  "Assert yourself—your safety matters.",
  "No means no. Always.",
  "Power comes from knowledge and preparation.",
  "Your strength is inspiring.",
  "You have what it takes to stay safe.",
  "Strong women look out for themselves and for each other.",
  "Courage is your birthright.",
  "Taking action is always stronger than staying silent.",
  "Trust your gut, even when others doubt.",
  "You are wise, resilient, and ready.",
  "Being cautious is never a weakness.",
  "A single act of self-defense can change your life.",
  "Invest in your personal safety.",
  "Self-defense is a form of self-expression.",
  "You are not a victim. You are a survivor—every day.",
  "Remember, seeking help is an act of bravery.",
  "Empowerment comes from knowledge.",
  "Choose to be confident, every day.",
  "You are a force to be reckoned with.",
  "Taking care of yourself is an act of resistance.",
  "You are your first and best line of defense.",
  "Awareness is the first step to empowerment.",
  "Prepare, don't scare.",
  "You have survived 100% of your worst days.",
  "Your safety is worth fighting for.",
  "Every woman deserves to feel safe and empowered.",
  "Stand up for yourself—you're worth it.",
  "Your courage inspires others to be brave.",
  "Safety is not optional—it's essential.",
  "You have the power to change your story.",
  "Never let anyone make you feel unsafe.",
  "Your strength is your superpower.",
  "Every woman has the right to walk freely.",
  "Protect yourself—you're irreplaceable.",
  "Your safety is non-negotiable.",
  "Be the woman you needed when you were younger.",
  "Your voice has power—use it.",
  "Safety is a right, not a privilege.",
  "You are capable of protecting yourself.",
  "Never underestimate your own strength.",
  "Your safety matters more than politeness.",
  "Be fierce, be fearless, be free.",
  "You are the author of your own safety story.",
  "Trust yourself—you know what's right.",
  "Your safety is your responsibility and your right.",
  "Be bold in protecting yourself.",
  "You have everything you need to stay safe.",
  "Your courage is contagious.",
  "Safety first, always.",
  "You are stronger than any challenge.",
  "Protect yourself like your life depends on it—because it does.",
  "Your safety is worth every effort.",
  "Be the hero of your own story.",
  "You have the right to feel safe everywhere.",
  "Your strength is your greatest asset.",
  "Never compromise on your safety.",
  "You are worth protecting.",
  "Your safety is your priority.",
  "Be confident in your ability to protect yourself.",
  "You have the power to create a safe world for yourself.",
  "Your safety is your birthright.",
  "Never let fear stop you from being safe.",
  "You are the guardian of your own safety.",
  "Your safety is your superpower.",
  "Be fearless in protecting yourself.",
  "You have the right to be safe and happy.",
  "Your safety is your strength.",
  "Never apologize for prioritizing your safety.",
  "You are the master of your own safety.",
  "Your safety is your freedom.",
  "Be unapologetic about protecting yourself.",
  "You have the right to feel safe in your own skin.",
  "Your safety is your peace of mind.",
  "Never let anyone compromise your safety.",
  "You are the architect of your own safety.",
  "Your safety is your sanctuary.",
  "Be relentless in protecting yourself.",
  "You have the right to be safe and free.",
  "Your safety is your foundation.",
  "Never settle for anything less than complete safety.",
  "You are the defender of your own safety.",
  "Your safety is your legacy.",
  "Be fierce in protecting what matters most—you.",
  "You have the right to live without fear.",
  "Your safety is your victory.",
  "Never let anyone take your safety away.",
  "You are the champion of your own safety.",
  "Your safety is your treasure.",
  "Be bold in claiming your right to safety.",
  "You have the power to make the world safer for yourself.",
  "Your safety is your revolution.",
  "Never underestimate the power of a safe woman.",
  "You are the warrior of your own safety.",
  "Your safety is your crown.",
  "Be unstoppable in protecting yourself.",
  "You have the right to be safe, strong, and free.",
  "Your safety is your masterpiece.",
  "Never let fear steal your safety.",
  "You are the queen of your own safety.",
  "Your safety is your empire.",
  "Be magnificent in protecting yourself.",
  "You have the right to be safe and powerful.",
  "Your safety is your magic.",
  "Never let anyone dim your safety light.",
  "You are the goddess of your own safety.",
  "Your safety is your universe.",
  "Be extraordinary in protecting yourself.",
  "You have the right to be safe and magnificent.",
  "Your safety is your infinity.",
  "Never let anything limit your safety.",
  "You are the universe of your own safety.",
  "Your safety is your eternity.",
  "Be infinite in protecting yourself.",
  "You have the right to be safe forever.",
  "Your safety is your immortality.",
  "Never let time steal your safety.",
  "You are the timeless guardian of your own safety.",
  "Your safety is your forever.",
  "Be eternal in protecting yourself.",
  "You have the right to be safe for all time.",
  "Your safety is your infinity and beyond.",
  "Never let anything end your safety.",
  "You are the endless protector of your own safety.",
  "Your safety is your endless journey.",
  "Be endless in protecting yourself.",
  "You have the right to be safe without end.",
  "Your safety is your endless story.",
  "Never let anything stop your safety story.",
  "You are the endless author of your own safety.",
  "Your safety is your endless adventure.",
  "Be endless in your safety adventure.",
  "You have the right to be safe in every adventure.",
  "Your safety is your endless quest.",
  "Never let anything end your safety quest.",
  "You are the endless hero of your own safety quest.",
  "Your safety is your endless victory.",
  "Be endless in your safety victories.",
  "You have the right to be safe and victorious forever.",
  "Your safety is your endless triumph.",
  "Never let anything end your safety triumphs.",
  "You are the endless champion of your own safety triumphs.",
  "Your safety is your endless glory.",
  "Be endless in your safety glory.",
  "You have the right to be safe and glorious forever.",
  "Your safety is your endless majesty.",
  "Never let anything end your safety majesty.",
  "You are the endless queen of your own safety majesty.",
  "Your safety is your endless sovereignty.",
  "Be endless in your safety sovereignty.",
  "You have the right to be safe and sovereign forever.",
  "Your safety is your endless dominion.",
  "Never let anything end your safety dominion.",
  "You are the endless ruler of your own safety dominion.",
  "Your safety is your endless kingdom.",
  "Be endless in your safety kingdom.",
  "You have the right to be safe and royal forever.",
  "Your safety is your endless empire.",
  "Never let anything end your safety empire.",
  "You are the endless empress of your own safety empire.",
  "Your safety is your endless realm.",
  "Be endless in your safety realm.",
  "You have the right to be safe and regal forever.",
  "Your safety is your endless throne.",
  "Never let anything end your safety throne.",
  "You are the endless monarch of your own safety throne.",
  "Your safety is your endless crown.",
  "Be endless in your safety crown.",
  "You have the right to be safe and crowned forever.",
  "Your safety is your endless scepter.",
  "Never let anything end your safety scepter.",
  "You are the endless sovereign of your own safety scepter.",
  "Your safety is your endless orb.",
  "Be endless in your safety orb.",
  "You have the right to be safe and orb-like forever.",
  "Your safety is your endless jewel.",
  "Never let anything end your safety jewel.",
  "You are the endless gem of your own safety jewel.",
  "Your safety is your endless diamond.",
  "Be endless in your safety diamond.",
  "You have the right to be safe and diamond-like forever.",
  "Your safety is your endless pearl.",
  "Never let anything end your safety pearl.",
  "You are the endless treasure of your own safety pearl.",
  "Your safety is your endless gold.",
  "Be endless in your safety gold.",
  "You have the right to be safe and golden forever.",
  "Your safety is your endless silver.",
  "Never let anything end your safety silver.",
  "You are the endless metal of your own safety silver.",
  "Your safety is your endless bronze.",
  "Be endless in your safety bronze.",
  "You have the right to be safe and bronze-like forever.",
  "Your safety is your endless platinum.",
  "Never let anything end your safety platinum.",
  "You are the endless element of your own safety platinum.",
  "Your safety is your endless titanium.",
  "Be endless in your safety titanium.",
  "You have the right to be safe and titanium-like forever.",
  "Your safety is your endless steel.",
  "Never let anything end your safety steel.",
  "You are the endless alloy of your own safety steel.",
  "Your safety is your endless iron.",
  "Be endless in your safety iron.",
  "You have the right to be safe and iron-like forever.",
  "Your safety is your endless copper.",
  "Never let anything end your safety copper.",
  "You are the endless conductor of your own safety copper.",
  "Your safety is your endless aluminum.",
  "Be endless in your safety aluminum.",
  "You have the right to be safe and aluminum-like forever.",
  "Your safety is your endless zinc.",
  "Never let anything end your safety zinc.",
  "You are the endless mineral of your own safety zinc.",
  "Your safety is your endless nickel.",
  "Be endless in your safety nickel.",
  "You have the right to be safe and nickel-like forever.",
  "Your safety is your endless cobalt.",
  "Never let anything end your safety cobalt.",
  "You are the endless metal of your own safety cobalt.",
  "Your safety is your endless chromium.",
  "Be endless in your safety chromium.",
  "You have the right to be safe and chromium-like forever.",
  "Your safety is your endless manganese.",
  "Never let anything end your safety manganese.",
  "You are the endless element of your own safety manganese.",
  "Your safety is your endless vanadium.",
  "Be endless in your safety vanadium.",
  "You have the right to be safe and vanadium-like forever.",
  "Your safety is your endless tungsten.",
  "Never let anything end your safety tungsten.",
  "You are the endless metal of your own safety tungsten.",
  "Your safety is your endless molybdenum.",
  "Be endless in your safety molybdenum.",
  "You have the right to be safe and molybdenum-like forever.",
  "Your safety is your endless tantalum.",
  "Never let anything end your safety tantalum.",
  "You are the endless element of your own safety tantalum.",
  "Your safety is your endless niobium.",
  "Be endless in your safety niobium.",
  "You have the right to be safe and niobium-like forever.",
  "Your safety is your endless hafnium.",
  "Never let anything end your safety hafnium.",
  "You are the endless metal of your own safety hafnium.",
  "Your safety is your endless zirconium.",
  "Be endless in your safety zirconium.",
  "You have the right to be safe and zirconium-like forever.",
  "Your safety is your endless titanium.",
  "Be endless in your safety titanium.",
  "You have the right to be safe and titanium-like forever.",
  "Your safety is your endless scandium.",
  "Never let anything end your safety scandium.",
  "You are the endless element of your own safety scandium.",
  "Your safety is your endless yttrium.",
  "Be endless in your safety yttrium.",
  "You have the right to be safe and yttrium-like forever.",
  "Your safety is your endless lanthanum.",
  "Never let anything end your safety lanthanum.",
  "You are the endless metal of your own safety lanthanum.",
  "Your safety is your endless cerium.",
  "Be endless in your safety cerium.",
  "You have the right to be safe and cerium-like forever.",
  "Your safety is your endless praseodymium.",
  "Never let anything end your safety praseodymium.",
  "You are the endless element of your own safety praseodymium.",
  "Your safety is your endless neodymium.",
  "Be endless in your safety neodymium.",
  "You have the right to be safe and neodymium-like forever.",
  "Your safety is your endless promethium.",
  "Never let anything end your safety promethium.",
  "You are the endless metal of your own safety promethium.",
  "Your safety is your endless samarium.",
  "Be endless in your safety samarium.",
  "You have the right to be safe and samarium-like forever.",
  "Your safety is your endless europium.",
  "Never let anything end your safety europium.",
  "You are the endless element of your own safety europium.",
  "Your safety is your endless gadolinium.",
  "Be endless in your safety gadolinium.",
  "You have the right to be safe and gadolinium-like forever.",
  "Your safety is your endless terbium.",
  "Never let anything end your safety terbium.",
  "You are the endless metal of your own safety terbium.",
  "Your safety is your endless dysprosium.",
  "Be endless in your safety dysprosium.",
  "You have the right to be safe and dysprosium-like forever.",
  "Your safety is your endless holmium.",
  "Never let anything end your safety holmium.",
  "You are the endless element of your own safety holmium.",
  "Your safety is your endless erbium.",
  "Be endless in your safety erbium.",
  "You have the right to be safe and erbium-like forever.",
  "Your safety is your endless thulium.",
  "Never let anything end your safety thulium.",
  "You are the endless metal of your own safety thulium.",
  "Your safety is your endless ytterbium.",
  "Be endless in your safety ytterbium.",
  "You have the right to be safe and ytterbium-like forever.",
  "Your safety is your endless lutetium.",
  "Never let anything end your safety lutetium.",
  "You are the endless element of your own safety lutetium.",
  "Your safety is your endless actinium.",
  "Be endless in your safety actinium.",
  "You have the right to be safe and actinium-like forever.",
  "Your safety is your endless thorium.",
  "Never let anything end your safety thorium.",
  "You are the endless metal of your own safety thorium.",
  "Your safety is your endless protactinium.",
  "Be endless in your safety protactinium.",
  "You have the right to be safe and protactinium-like forever.",
  "Your safety is your endless uranium.",
  "Never let anything end your safety uranium.",
  "You are the endless element of your own safety uranium.",
  "Your safety is your endless neptunium.",
  "Be endless in your safety neptunium.",
  "You have the right to be safe and neptunium-like forever.",
  "Your safety is your endless plutonium.",
  "Never let anything end your safety plutonium.",
  "You are the endless metal of your own safety plutonium.",
  "Your safety is your endless americium.",
  "Be endless in your safety americium.",
  "You have the right to be safe and americium-like forever.",
  "Your safety is your endless curium.",
  "Never let anything end your safety curium.",
  "You are the endless element of your own safety curium.",
  "Your safety is your endless berkelium.",
  "Be endless in your safety berkelium.",
  "You have the right to be safe and berkelium-like forever.",
  "Your safety is your endless californium.",
  "Never let anything end your safety californium.",
  "You are the endless metal of your own safety californium.",
  "Your safety is your endless einsteinium.",
  "Be endless in your safety einsteinium.",
  "You have the right to be safe and einsteinium-like forever.",
  "Your safety is your endless fermium.",
  "Never let anything end your safety fermium.",
  "You are the endless element of your own safety fermium.",
  "Your safety is your endless mendelevium.",
  "Be endless in your safety mendelevium.",
  "You have the right to be safe and mendelevium-like forever.",
  "Your safety is your endless nobelium.",
  "Never let anything end your safety nobelium.",
  "You are the endless metal of your own safety nobelium.",
  "Your safety is your endless lawrencium.",
  "Be endless in your safety lawrencium.",
  "You have the right to be safe and lawrencium-like forever.",
  "Your safety is your endless rutherfordium.",
  "Never let anything end your safety rutherfordium.",
  "You are the endless element of your own safety rutherfordium.",
  "Your safety is your endless dubnium.",
  "Be endless in your safety dubnium.",
  "You have the right to be safe and dubnium-like forever.",
  "Your safety is your endless seaborgium.",
  "Never let anything end your safety seaborgium.",
  "You are the endless metal of your own safety seaborgium.",
  "Your safety is your endless bohrium.",
  "Be endless in your safety bohrium.",
  "You have the right to be safe and bohrium-like forever.",
  "Your safety is your endless hassium.",
  "Never let anything end your safety hassium.",
  "You are the endless element of your own safety hassium.",
  "Your safety is your endless meitnerium.",
  "Be endless in your safety meitnerium.",
  "You have the right to be safe and meitnerium-like forever.",
  "Your safety is your endless darmstadtium.",
  "Never let anything end your safety darmstadtium.",
  "You are the endless metal of your own safety darmstadtium.",
  "Your safety is your endless roentgenium.",
  "Be endless in your safety roentgenium.",
  "You have the right to be safe and roentgenium-like forever.",
  "Your safety is your endless copernicium.",
  "Never let anything end your safety copernicium.",
  "You are the endless element of your own safety copernicium.",
  "Your safety is your endless nihonium.",
  "Be endless in your safety nihonium.",
  "You have the right to be safe and nihonium-like forever.",
  "Your safety is your endless flerovium.",
  "Never let anything end your safety flerovium.",
  "You are the endless metal of your own safety flerovium.",
  "Your safety is your endless moscovium.",
  "Be endless in your safety moscovium.",
  "You have the right to be safe and moscovium-like forever.",
  "Your safety is your endless livermorium.",
  "Never let anything end your safety livermorium.",
  "You are the endless element of your own safety livermorium.",
  "Your safety is your endless tennessine.",
  "Be endless in your safety tennessine.",
  "You have the right to be safe and tennessine-like forever.",
  "Your safety is your endless oganesson.",
  "Never let anything end your safety oganesson.",
  "You are the endless element of your own safety oganesson.",
  "Your safety is your endless hydrogen.",
  "Be endless in your safety hydrogen.",
  "You have the right to be safe and hydrogen-like forever.",
  "Your safety is your endless helium.",
  "Never let anything end your safety helium.",
  "You are the endless metal of your own safety helium.",
  "Your safety is your endless lithium.",
  "Be endless in your safety lithium.",
  "You have the right to be safe and lithium-like forever.",
  "Your safety is your endless beryllium.",
  "Never let anything end your safety beryllium.",
  "You are the endless element of your own safety beryllium.",
  "Your safety is your endless boron.",
  "Be endless in your safety boron.",
  "You have the right to be safe and boron-like forever.",
  "Your safety is your endless carbon.",
  "Never let anything end your safety carbon.",
  "You are the endless metal of your own safety carbon.",
  "Your safety is your endless nitrogen.",
  "Be endless in your safety nitrogen.",
  "You have the right to be safe and nitrogen-like forever.",
  "Your safety is your endless oxygen.",
  "Never let anything end your safety oxygen.",
  "You are the endless element of your own safety oxygen.",
  "Your safety is your endless fluorine.",
  "Be endless in your safety fluorine.",
  "You have the right to be safe and fluorine-like forever.",
  "Your safety is your endless neon.",
  "Never let anything end your safety neon.",
  "You are the endless metal of your own safety neon.",
  "Your safety is your endless sodium.",
  "Be endless in your safety sodium.",
  "You have the right to be safe and sodium-like forever.",
  "Your safety is your endless magnesium.",
  "Never let anything end your safety magnesium.",
  "You are the endless element of your own safety magnesium.",
  "Your safety is your endless aluminum.",
  "Be endless in your safety aluminum.",
  "You have the right to be safe and aluminum-like forever.",
  "Your safety is your endless silicon.",
  "Never let anything end your safety silicon.",
  "You are the endless metal of your own safety silicon.",
  "Your safety is your endless phosphorus.",
  "Be endless in your safety phosphorus.",
  "You have the right to be safe and phosphorus-like forever.",
  "Your safety is your endless sulfur.",
  "Never let anything end your safety sulfur.",
  "You are the endless element of your own safety sulfur.",
  "Your safety is your endless chlorine.",
  "Be endless in your safety chlorine.",
  "You have the right to be safe and chlorine-like forever.",
  "Your safety is your endless argon.",
  "Never let anything end your safety argon.",
  "You are the endless metal of your own safety argon.",
  "Your safety is your endless potassium.",
  "Be endless in your safety potassium.",
  "You have the right to be safe and potassium-like forever.",
  "Your safety is your endless calcium.",
  "Be endless in your safety calcium.",
  "You have the right to be safe and calcium-like forever.",
  "Your safety is your endless scandium.",
  "Never let anything end your safety scandium.",
  "You are the endless element of your own safety scandium.",
  "Your safety is your endless titanium.",
  "Be endless in your safety titanium.",
  "You have the right to be safe and titanium-like forever.",
  "Your safety is your endless vanadium.",
  "Be endless in your safety vanadium.",
  "You have the right to be safe and vanadium-like forever.",
  "Your safety is your endless chromium.",
  "Never let anything end your safety chromium.",
  "You are the endless metal of your own safety chromium.",
  "Your safety is your endless manganese.",
  "Be endless in your safety manganese.",
  "You have the right to be safe and manganese-like forever.",
  "Your safety is your endless iron.",
  "Never let anything end your safety iron.",
  "You are the endless element of your own safety iron.",
  "Your safety is your endless cobalt.",
  "Be endless in your safety cobalt.",
  "You have the right to be safe and cobalt-like forever.",
  "Your safety is your endless nickel.",
  "Never let anything end your safety nickel.",
  "You are the endless metal of your own safety nickel.",
  "Your safety is your endless copper.",
  "Be endless in your safety copper.",
  "You have the right to be safe and copper-like forever.",
  "Your safety is your endless zinc.",
  "Never let anything end your safety zinc.",
  "You are the endless element of your own safety zinc.",
  "Your safety is your endless gallium.",
  "Be endless in your safety gallium.",
  "You have the right to be safe and gallium-like forever.",
  "Your safety is your endless germanium.",
  "Never let anything end your safety germanium.",
  "You are the endless metal of your own safety germanium.",
  "Your safety is your endless arsenic.",
  "Be endless in your safety arsenic.",
  "You have the right to be safe and arsenic-like forever.",
  "Your safety is your endless selenium.",
  "Never let anything end your safety selenium.",
  "You are the endless element of your own safety selenium.",
  "Your safety is your endless bromine.",
  "Be endless in your safety bromine.",
  "You have the right to be safe and bromine-like forever.",
  "Your safety is your endless krypton.",
  "Never let anything end your safety krypton.",
  "You are the endless metal of your own safety krypton.",
  "Your safety is your endless rubidium.",
  "Be endless in your safety rubidium.",
  "You have the right to be safe and rubidium-like forever.",
  "Your safety is your endless strontium.",
  "Be endless in your safety strontium.",
  "You have the right to be safe and strontium-like forever.",
  "Your safety is your endless yttrium.",
  "Never let anything end your safety yttrium.",
  "You are the endless element of your own safety yttrium.",
  "Your safety is your endless zirconium.",
  "Be endless in your safety zirconium.",
  "You have the right to be safe and zirconium-like forever.",
  "Your safety is your endless niobium.",
  "Never let anything end your safety niobium.",
  "You are the endless metal of your own safety niobium.",
  "Your safety is your endless molybdenum.",
  "Be endless in your safety molybdenum.",
  "You have the right to be safe and molybdenum-like forever.",
  "Your safety is your endless technetium.",
  "Never let anything end your safety technetium.",
  "You are the endless element of your own safety technetium.",
  "Your safety is your endless ruthenium.",
  "Be endless in your safety ruthenium.",
  "You have the right to be safe and ruthenium-like forever.",
  "Your safety is your endless rhodium.",
  "Never let anything end your safety rhodium.",
  "You are the endless metal of your own safety rhodium.",
  "Your safety is your endless palladium.",
  "Be endless in your safety palladium.",
  "You have the right to be safe and palladium-like forever.",
  "Your safety is your endless silver.",
  "Never let anything end your safety silver.",
  "You are the endless element of your own safety silver.",
  "Your safety is your endless cadmium.",
  "Be endless in your safety cadmium.",
  "You have the right to be safe and cadmium-like forever.",
  "Your safety is your endless indium.",
  "Never let anything end your safety indium.",
  "You are the endless metal of your own safety indium.",
  "Your safety is your endless tin.",
  "Be endless in your safety tin.",
  "You have the right to be safe and tin-like forever.",
  "Your safety is your endless antimony.",
  "Never let anything end your safety antimony.",
  "You are the endless element of your own safety antimony.",
  "Your safety is your endless tellurium.",
  "Be endless in your safety tellurium.",
  "You have the right to be safe and tellurium-like forever.",
  "Your safety is your endless iodine.",
  "Never let anything end your safety iodine.",
  "You are the endless metal of your own safety iodine.",
  "Your safety is your endless xenon.",
  "Be endless in your safety xenon.",
  "You have the right to be safe and xenon-like forever.",
  "Your safety is your endless cesium.",
  "Never let anything end your safety cesium.",
  "You are the endless element of your own safety cesium.",
  "Your safety is your endless barium.",
  "Be endless in your safety barium.",
  "You have the right to be safe and barium-like forever.",
  "Your safety is your endless lanthanum.",
  "Never let anything end your safety lanthanum.",
  "You are the endless metal of your own safety lanthanum.",
  "Your safety is your endless cerium.",
  "Be endless in your safety cerium.",
  "You have the right to be safe and cerium-like forever.",
  "Your safety is your endless praseodymium.",
  "Never let anything end your safety praseodymium.",
  "You are the endless element of your own safety praseodymium.",
  "Your safety is your endless neodymium.",
  "Be endless in your safety neodymium.",
  "You have the right to be safe and neodymium-like forever.",
  "Your safety is your endless promethium.",
  "Never let anything end your safety promethium.",
  "You are the endless metal of your own safety promethium.",
  "Your safety is your endless samarium.",
  "Be endless in your safety samarium.",
  "You have the right to be safe and samarium-like forever.",
  "Your safety is your endless europium.",
  "Never let anything end your safety europium.",
  "You are the endless element of your own safety europium.",
  "Your safety is your endless gadolinium.",
  "Be endless in your safety gadolinium.",
  "You have the right to be safe and gadolinium-like forever.",
  "Your safety is your endless terbium.",
  "Never let anything end your safety terbium.",
  "You are the endless metal of your own safety terbium.",
  "Your safety is your endless dysprosium.",
  "Be endless in your safety dysprosium.",
  "You have the right to be safe and dysprosium-like forever.",
  "Your safety is your endless holmium.",
  "Never let anything end your safety holmium.",
  "You are the endless element of your own safety holmium.",
  "Your safety is your endless erbium.",
  "Be endless in your safety erbium.",
  "You have the right to be safe and erbium-like forever.",
  "Your safety is your endless thulium.",
  "Never let anything end your safety thulium.",
  "You are the endless metal of your own safety thulium.",
  "Your safety is your endless ytterbium.",
  "Be endless in your safety ytterbium.",
  "You have the right to be safe and ytterbium-like forever.",
  "Your safety is your endless lutetium.",
  "Never let anything end your safety lutetium.",
  "You are the endless element of your own safety lutetium.",
  "Your safety is your endless hafnium.",
  "Never let anything end your safety hafnium.",
  "You are the endless metal of your own safety hafnium.",
  "Your safety is your endless tantalum.",
  "Be endless in your safety tantalum.",
  "You are the endless element of your own safety tantalum.",
  "Your safety is your endless tungsten.",
  "Never let anything end your safety tungsten.",
  "You are the endless metal of your own safety tungsten.",
  "Your safety is your endless rhenium.",
  "Be endless in your safety rhenium.",
  "You have the right to be safe and rhenium-like forever.",
  "Your safety is your endless osmium.",
  "Never let anything end your safety osmium.",
  "You are the endless element of your own safety osmium.",
  "Your safety is your endless iridium.",
  "Be endless in your safety iridium.",
  "You have the right to be safe and iridium-like forever.",
  "Your safety is your endless platinum.",
  "Never let anything end your safety platinum.",
  "You are the endless metal of your own safety platinum.",
  "Your safety is your endless gold.",
  "Be endless in your safety gold.",
  "You have the right to be safe and golden forever.",
  "Your safety is your endless mercury.",
  "Never let anything end your safety mercury.",
  "You are the endless element of your own safety mercury.",
  "Your safety is your endless thallium.",
  "Be endless in your safety thallium.",
  "You have the right to be safe and thallium-like forever.",
  "Your safety is your endless lead.",
  "Never let anything end your safety lead.",
  "You are the endless metal of your own safety lead.",
  "Your safety is your endless bismuth.",
  "Be endless in your safety bismuth.",
  "You have the right to be safe and bismuth-like forever.",
  "Your safety is your endless polonium.",
  "Never let anything end your safety polonium.",
  "You are the endless element of your own safety polonium.",
  "Your safety is your endless astatine.",
  "Be endless in your safety astatine.",
  "You have the right to be safe and astatine-like forever.",
  "Your safety is your endless radon.",
  "Never let anything end your safety radon.",
  "You are the endless metal of your own safety radon.",
  "Your safety is your endless francium.",
  "Be endless in your safety francium.",
  "You have the right to be safe and francium-like forever.",
  "Your safety is your endless radium.",
  "Be endless in your safety radium.",
  "You have the right to be safe and radium-like forever.",
  "Your safety is your endless actinium.",
  "Never let anything end your safety actinium.",
  "You are the endless element of your own safety actinium.",
  "Your safety is your endless thorium.",
  "Never let anything end your safety thorium.",
  "You are the endless metal of your own safety thorium.",
  "Your safety is your endless protactinium.",
  "Be endless in your safety protactinium.",
  "You have the right to be safe and protactinium-like forever.",
  "Your safety is your endless uranium.",
  "Never let anything end your safety uranium.",
  "You are the endless element of your own safety uranium.",
  "Your safety is your endless neptunium.",
  "Be endless in your safety neptunium.",
  "You have the right to be safe and neptunium-like forever.",
  "Your safety is your endless plutonium.",
  "Never let anything end your safety plutonium.",
  "You are the endless metal of your own safety plutonium.",
  "Your safety is your endless americium.",
  "Be endless in your safety americium.",
  "You have the right to be safe and americium-like forever.",
  "Your safety is your endless curium.",
  "Never let anything end your safety curium.",
  "You are the endless element of your own safety curium.",
  "Your safety is your endless berkelium.",
  "Be endless in your safety berkelium.",
  "You have the right to be safe and berkelium-like forever.",
  "Your safety is your endless californium.",
  "Never let anything end your safety californium.",
  "You are the endless metal of your own safety californium.",
  "Your safety is your endless einsteinium.",
  "Be endless in your safety einsteinium.",
  "You have the right to be safe and einsteinium-like forever.",
  "Your safety is your endless fermium.",
  "Never let anything end your safety fermium.",
  "You are the endless element of your own safety fermium.",
  "Your safety is your endless mendelevium.",
  "Be endless in your safety mendelevium.",
  "You have the right to be safe and mendelevium-like forever.",
  "Your safety is your endless nobelium.",
  "Never let anything end your safety nobelium.",
  "You are the endless metal of your own safety nobelium.",
  "Your safety is your endless lawrencium.",
  "Never let anything end your safety lawrencium.",
  "You are the endless element of your own safety lawrencium.",
  "Your safety is your endless rutherfordium.",
  "Never let anything end your safety rutherfordium.",
  "You are the endless metal of your own safety rutherfordium.",
  "Your safety is your endless dubnium.",
  "Be endless in your safety dubnium.",
  "You have the right to be safe and dubnium-like forever.",
  "Your safety is your endless seaborgium.",
  "Never let anything end your safety seaborgium.",
  "You are the endless element of your own safety seaborgium.",
  "Your safety is your endless bohrium.",
  "Never let anything end your safety bohrium.",
  "You are the endless metal of your own safety bohrium.",
  "Your safety is your endless hassium.",
  "Never let anything end your safety hassium.",
  "You are the endless element of your own safety hassium.",
  "Your safety is your endless meitnerium.",
  "Be endless in your safety meitnerium.",
  "You have the right to be safe and meitnerium-like forever.",
  "Your safety is your endless darmstadtium.",
  "Never let anything end your safety darmstadtium.",
  "You are the endless metal of your own safety darmstadtium.",
  "Your safety is your endless roentgenium.",
  "Be endless in your safety roentgenium.",
  "You have the right to be safe and roentgenium-like forever.",
  "Your safety is your endless copernicium.",
  "Never let anything end your safety copernicium.",
  "You are the endless element of your own safety copernicium.",
  "Your safety is your endless nihonium.",
  "Never let anything end your safety nihonium.",
  "You are the endless metal of your own safety nihonium.",
  "Your safety is your endless flerovium.",
  "Never let anything end your safety flerovium.",
  "You are the endless element of your own safety flerovium.",
  "Your safety is your endless moscovium.",
  "Never let anything end your safety moscovium.",
  "You are the endless metal of your own safety moscovium.",
  "Your safety is your endless livermorium.",
  "Never let anything end your safety livermorium.",
  "You are the endless element of your own safety livermorium.",
  "Your safety is your endless tennessine.",
  "Never let anything end your safety tennessine.",
  "You are the endless metal of your own safety tennessine.",
  "Your safety is your endless oganesson.",
  "Never let anything end your safety oganesson.",
  "You are the endless element of your own safety oganesson."
];

async function populateQuotes() {
  try {
    console.log('Starting to populate quotes...');
    
    // Clear existing quotes
    const existingQuotes = await db.collection('motivationalQuotes').get();
    const batch = db.batch();
    
    existingQuotes.docs.forEach(doc => {
      batch.delete(doc.ref);
    });
    
    await batch.commit();
    console.log('Cleared existing quotes');
    
    // Add new quotes
    const quotesBatch = db.batch();
    
    motivationalQuotes.forEach((quote, index) => {
      const docRef = db.collection('motivationalQuotes').doc();
      quotesBatch.set(docRef, {
        text: quote,
        index: index,
        createdAt: admin.firestore.FieldValue.serverTimestamp(),
        isActive: true
      });
    });
    
    await quotesBatch.commit();
    console.log(`Successfully added ${motivationalQuotes.length} quotes to database`);
    
  } catch (error) {
    console.error('Error populating quotes:', error);
  }
}

// Run the script
populateQuotes().then(() => {
  console.log('Quote population completed');
  process.exit(0);
}).catch(error => {
  console.error('Script failed:', error);
  process.exit(1);
});
